[package]
name = "hello-rust"
version = "0.2.0"
authors = ["delankallen <delankallen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
